[package]
name = "oddsstream-service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
linera-sdk = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }